#!/bin/bash

# Last update by pavroo July 28, 2021

LANGUAGE=${LANG:0:2}
EN=`echo $LANGUAGE | grep en`
ES=`echo $LANGUAGE | grep es`
PL=`echo $LANGUAGE | grep pl`
RU=`echo $LANGUAGE | grep ru`

if [ "$ES" != "" ]; then
	LANGUAGE="$LANGUAGE"
elif [ "$PL" != "" ]; then
	LANGUAGE="$LANGUAGE"
elif [ "$RU" != "" ]; then
	LANGUAGE="$LANGUAGE"
else
	LANGUAGE="en"
fi

POS="--center --width 800 --height 550"
HTML="--html --browser"
# index page

#TESTMODE=`mount | grep squashfs`
#if [ "$TESTMODE" != "" ] && [ -d /home/live ]; then
#
#	if [ "$1" = "" ]; then
#		yad --window-icon=/usr/share/pixmaps/sparky-welcome.png $POS $HTML --uri="index-live.html" --user-agent="$LANGUAGE" --uri-handler="./handler"
#	elif [ "$1" = "glowna" ]; then
#		yad --window-icon=/usr/share/pixmaps/sparky-welcome.com $POS $HTML --uri="index-live.html" --user-agent="$LANGUAGE" --uri-handler="./handler"
#	fi
#	
#else

	if [ "$1" = "" ]; then
		yad --window-icon=/usr/share/pixmaps/sparky-welcome.png $POS $HTML --uri="index.html" --user-agent="$LANGUAGE" --uri-handler="./handler"
	elif [ "$1" = "glowna" ]; then
		yad --window-icon=/usr/share/pixmaps/sparky-welcome.com $POS $HTML --uri="index.html" --user-agent="$LANGUAGE" --uri-handler="./handler"
	fi

#fi

exit 0
