#!/bin/bash

# Last update by pavroo July 2, 2022

LANGUAGE=${LANG:0:2}
EL=`echo $LANGUAGE | grep el`
EN=`echo $LANGUAGE | grep en`
ESAR=`echo $LANGUAGE | grep es_AR`
ESES=`echo $LANGUAGE | grep es_ES`
HU=`echo $LANGUAGE | grep hu`
IT=`echo $LANGUAGE | grep it`
PL=`echo $LANGUAGE | grep pl`
RU=`echo $LANGUAGE | grep ru`

if [ "$ESAR" != "" ]; then
	LANGUAGE="$LANGUAGE"
elif [ "$ESES" != "" ]; then
	LANGUAGE="$LANGUAGE"
elif [ "$HU" != "" ]; then
	LANGUAGE="$LANGUAGE"
elif [ "$IT" != "" ]; then
	LANGUAGE="$LANGUAGE"
elif [ "$PL" != "" ]; then
	LANGUAGE="$LANGUAGE"
elif [ "$RU" != "" ]; then
	LANGUAGE="$LANGUAGE"
else
	LANGUAGE="en"
fi

POS="--center --width 800 --height 550"
HTML="--html --browser"
# index page
if [ "$1" = "" ]; then
	yad --window-icon=/usr/share/pixmaps/sparky-welcome.png $POS $HTML --uri="index.html" --user-agent="$LANGUAGE" --uri-handler="./handler"
elif [ "$1" = "glowna" ]; then
	yad --window-icon=/usr/share/pixmaps/sparky-welcome.com $POS $HTML --uri="index.html" --user-agent="$LANGUAGE" --uri-handler="./handler"
fi

exit 0
